version: '3'

services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  php:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/app
    depends_on:
      - redis

